# Generated by Django 5.2 on 2025-04-26 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cliente_email_alter_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener solo números.', regex='^\\d+$'), django.core.validators.MinLengthValidator(10, message='El teléfono debe tener 10  números.'), django.core.validators.MaxLengthValidator(10, 'El teléfono debe tener 10  números.')]),
        ),
    ]
