# Generated by Django 5.2 on 2025-04-26 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_apellido_alter_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999, message='Valor demasiado grande. Límite máximo de 10 números')])),
                ('fecha', models.DateField()),
                ('Descripcion', models.CharField(validators=[django.core.validators.MaxLengthValidator(100, message='Descripción demasiado larga')])),
            ],
        ),
    ]
