# Generated by Django 5.2 on 2025-04-27 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_egreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egreso',
            name='Descripcion',
        ),
        migrations.AlterField(
            model_name='egreso',
            name='valor',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='egreso',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=100, validators=[django.core.validators.MaxLengthValidator(limit_value=100, message='Descripción demasiado larga (máx. 100 caracteres)')]),
            preserve_default=False,
        ),
    ]
