# Generated by Django 5.2 on 2025-04-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_apellido_alter_cliente_nombre_and_more'),
        ('core', '0005_alter_empleado_cedula_alter_empleado_celular_and_more'),
    ]

    operations = [
    ]
