# Generated by Django 5.2 on 2025-04-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_egreso_descripcion_alter_egreso_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='descripcion',
            field=models.TextField(blank=True, max_length=110),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='fecha',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10),
        ),
    ]
