# Generated by Django 5.2 on 2025-04-30 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_empleado_cedula_alter_empleado_celular'),
        ('core', '0007_alter_empleado_cedula_alter_empleado_celular'),
    ]

    operations = [
    ]
