# Generated by Django 5.2 on 2025-04-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_empleado_cedula_alter_empleado_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='estado',
            field=models.CharField(choices=[('cotización', 'Cotización'), ('reparación', 'En reparación'), ('prueba', 'En prueba'), ('listo', 'Listo para entrega'), ('entregado', 'Entregado')], default='cotización', max_length=15),
        ),
    ]
