# Generated by Django 5.2 on 2025-04-30 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_egreso_descripcion_alter_egreso_fecha_and_more'),
        ('core', '0007_alter_empleado_cedula_alter_empleado_celular'),
    ]

    operations = [
    ]
