# Generated by Django 5.2 on 2025-04-30 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_passwordresettoken'),
        ('core', '0010_alter_reparacion_estado'),
    ]

    operations = [
    ]
