# Generated by Django 5.2 on 2025-04-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20250430_0018'),
        ('core', '0012_merge_20250430_0012'),
    ]

    operations = [
    ]
