# Generated by Django 5.2 on 2025-05-01 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20250430_0922'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Egreso',
        ),
    ]
