# Generated by Django 5.2 on 2025-05-02 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_egreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(30, 'El apellido debe tener maximo 30 caracteres')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(20, 'El nombre debe tener maximo 20 caracteres')]),
        ),
    ]
