# Generated by Django 5.2 on 2025-05-11 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_reloj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reloj',
            old_name='dueño',
            new_name='dueno',
        ),
        migrations.AlterField(
            model_name='reloj',
            name='comision',
            field=models.CharField(editable=False, max_length=20, validators=[django.core.validators.RegexValidator(message='La comision debe ser un número válido', regex='^\\d+$'), django.core.validators.MaxLengthValidator(20, 'La comision no puede exceder los 20 caracteres')]),
        ),
    ]
