# Generated by Django 5.2 on 2025-05-11 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_dueño_reloj_dueno_alter_reloj_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reloj',
            name='comision',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='La comision debe ser un número válido', regex='^\\d+$'), django.core.validators.MaxLengthValidator(20, 'La comision no puede exceder los 20 caracteres')]),
        ),
    ]
