# Generated by Django 5.2 on 2025-05-16 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaPila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('pila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='core.pilas')),
            ],
        ),
    ]
