# Generated by Django 5.2 on 2025-05-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ingreso'),
        ('core', '0022_reloj_cliente'),
    ]

    operations = [
    ]
