# Generated by Django 5.2 on 2025-05-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_0022_ingreso_0022_reloj_cliente'),
        ('core', '0023_ventapila'),
    ]

    operations = [
    ]
