# Generated by Django 5.2 on 2025-06-01 21:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_reloj_tiene_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='reloj',
            name='metodo_pago',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('ABONO', 'Abono')], default='CONTADO', max_length=20),
        ),
        migrations.AddField(
            model_name='reloj',
            name='saldo_pendiente',
            field=models.CharField(default='0', max_length=20, validators=[django.core.validators.RegexValidator(message='El saldo pendiente debe ser un número válido', regex='^\\d+$'), django.core.validators.MaxLengthValidator(20, 'El saldo pendiente no puede exceder los 20 caracteres')]),
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El monto debe ser un número válido', regex='^\\d+$'), django.core.validators.MaxLengthValidator(20, 'El monto no puede exceder los 20 caracteres')], verbose_name='Monto del abono')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha del abono')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('reloj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='core.reloj')),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'ordering': ['-fecha'],
            },
        ),
    ]
