# Generated by Django 5.2 on 2025-06-12 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_ventapila_valor_total'),
        ('core', '0026_reloj_metodo_pago_reloj_saldo_pendiente_abono'),
    ]

    operations = [
    ]
