# Generated by Django 5.2 on 2025-06-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_ventapila_precio_unitario_alter_reloj_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='mantenimiento',
            field=models.BooleanField(default=False),
        ),
    ]
