# Generated by Django 5.2 on 2025-06-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_pilas_precio'),
        ('core', '0029_merge_20250623_2258'),
    ]

    operations = [
    ]
