# Generated by Django 5.2 on 2025-06-28 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_merge_20250628_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventapila',
            name='valor_total',
        ),
    ]
