# Generated by Django 5.2 on 2025-04-26 17:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cliente_email_alter_cliente_apellido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.BigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.BigIntegerField()),
                ('cargo', models.CharField(choices=[('Técnico', 'Técnico'), ('Secretario/a', 'Secretario/a')], max_length=20)),
                ('salario', models.BigIntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener solo números.', regex='^\\d+$'), django.core.validators.MinLengthValidator(10, message='El teléfono debe tener 10  números.'), django.core.validators.MaxLengthValidator(10, 'El teléfono debe tener 10  números.')]),
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_reloj', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=500)),
                ('codigo_orden', models.CharField(max_length=10, unique=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateField()),
                ('precio', models.PositiveIntegerField()),
                ('espacio_fisico', models.CharField(max_length=15)),
                ('estado', models.CharField(choices=[('cotización', 'Cotización'), ('reparación', 'En reparación'), ('prueba', 'En prueba'), ('entregado', 'Entregado')], default='cotización', max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('tecnico', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
