# Generated by Django 5.2 on 2025-04-26 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empleado_alter_cliente_apellido_alter_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='tecnico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones', to='core.empleado'),
        ),
    ]
