# Generated by Django 5.2 on 2025-04-28 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20250428_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe contener solo números y tener máximo 10 dígitos.', regex='^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='celular',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de celular debe comenzar con 3 y tener 10 dígitos en total.', regex='^3\\d{9}$')]),
        ),
    ]
