# Generated by Django 5.2 on 2025-04-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_egreso_descripcion_alter_egreso_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='descripcion',
            field=models.TextField(max_length=110),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='valor',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
