# Generated by Django 5.2 on 2025-04-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_reparacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='estado',
            field=models.CharField(choices=[('Cotización', 'Cotización'), ('Reparación', 'En reparación'), ('Prueba', 'En prueba'), ('Listo', 'Listo para entrega'), ('Entregado', 'Entregado')], default='cotización', max_length=15),
        ),
    ]
