# Generated by Django 5.2 on 2025-04-30 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20250429_1904'),
        ('core', '0011_merge_20250429_2154'),
    ]

    operations = [
    ]
