# Generated by Django 5.2 on 2025-05-02 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20250430_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=30)),
                ('precio', models.CharField(max_length=10)),
                ('cantidad', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Egreso',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(30, 'El apellido debe tener maximo 30 caracteres')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(20, 'El nombre debe tener maximo 20 caracteres')]),
        ),
    ]
