# Generated by Django 5.2 on 2025-05-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pilas_delete_egreso_alter_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilas',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='pilas',
            name='cantidad',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='pilas',
            name='codigo',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='pilas',
            name='precio',
            field=models.CharField(max_length=6),
        ),
    ]
