# Generated by Django 5.2 on 2025-05-05 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_pilas_descripcion_alter_pilas_cantidad_and_more'),
        ('core', '0016_alter_cliente_apellido_alter_cliente_nombre'),
    ]

    operations = [
    ]
