# Generated by Django 5.2 on 2025-05-10 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_egreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reloj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30, 'Nombre de marca demasiado largo')])),
                ('referencia', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30, 'Referencia demasiado larga')])),
                ('precio', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El precio debe ser un número válido', regex='^\\d+$'), django.core.validators.MaxLengthValidator(20, 'El precio no puede exceder los 20 caracteres')])),
                ('comision', models.IntegerField(editable=False, validators=[django.core.validators.MinValueValidator(0, 'La comisión debe ser mayor o igual a 0.')])),
                ('dueño', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, 'Nombre del dueño demasiado largo')])),
                ('descripcion', models.TextField(max_length=150, validators=[django.core.validators.MaxLengthValidator(150, 'Descripción demasiado larga')])),
                ('tipo', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado'), ('SEMI', 'Seminuevo')], max_length=20)),
                ('estado', models.CharField(choices=[('VENDIDO', 'Vendido'), ('DISPONIBLE', 'Disponible')], default='DISPONIBLE', max_length=20)),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
    ]
