# Generated by Django 5.2 on 2025-05-17 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_reloj_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='reloj',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
    ]
