# Generated by Django 5.2 on 2025-05-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20250518_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventapila',
            name='valor_total',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
