# Generated by Django 5.2 on 2025-06-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20250518_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='reloj',
            name='tiene_comision',
            field=models.BooleanField(default=False, verbose_name='¿Tiene comisión?'),
        ),
    ]
