# Generated by Django 5.2 on 2025-05-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_ventapila_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventapila',
            name='valor_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
