# Generated by Django 5.2 on 2025-06-10 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_reloj_metodo_pago_reloj_saldo_pendiente_abono'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventapila',
            name='precio_unitario',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reloj',
            name='metodo_pago',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('ABONO', 'Abono')], default='ABONO', max_length=20),
        ),
        migrations.AlterField(
            model_name='reloj',
            name='saldo_pendiente',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El saldo pendiente debe ser un número válido', regex='^\\d+$'), django.core.validators.MaxLengthValidator(20, 'El saldo pendiente no puede exceder los 20 caracteres')]),
        ),
    ]
