# Generated by Django 5.2 on 2025-06-24 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_20250611_2222'),
        ('core', '0028_reparacion_mantenimiento'),
    ]

    operations = [
    ]
