# Generated by Django 5.2 on 2025-06-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_reparacion_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilas',
            name='precio',
            field=models.CharField(blank=True, default='0', max_length=6),
        ),
    ]
