# Generated by Django 4.2.7 on 2025-11-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_remove_ventapila_valor_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="salario",
            field=models.CharField(max_length=20),
        ),
    ]
